os: Visual Studio 2015
version: 1.0.{build}
environment:
  PYTHON: "C:\\Python34"

  matrix:
  - BUILD_VARIANT: debug
    QTDIR: C:\Qt\5.9\msvc2015_64

  - BUILD_VARIANT: release
    QTDIR: C:\Qt\5.9\msvc2015_64

  - BUILD_VARIANT: debug
    QTDIR: C:\Qt\5.8\msvc2015_64

  - BUILD_VARIANT: release
    QTDIR: C:\Qt\5.8\msvc2015_64

  - BUILD_VARIANT: debug
    QTDIR: C:\Qt\5.7\msvc2015_64

  - BUILD_VARIANT: release
    QTDIR: C:\Qt\5.7\msvc2015_64

install:
  - cmd: dir C:\Qt\
  - cmd: dir %QTDIR%\..
  - cmd: git submodule update --init --recursive
  - cmd: set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\install
  - cmd: curl -fsS -o rclone.zip https://downloads.rclone.org/rclone-current-windows-amd64.zip && 7z e rclone.zip
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%;%cd%
  - cmd: set SCRIPTS_DIR=%APPVEYOR_BUILD_FOLDER%\scripts
  - cmd: dir %cd%
  - cmd: python -m pip install --upgrade pip && pip install --upgrade wheel -V && pip install --upgrade PySide easyprocess Pillow pyscreenshot pyvirtualdisplay -V
  - python --version
  - pip --version
  - qbs --version
  - ps: $screen_resolution = '1280x800'; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- cmd: >-

    qbs setup-toolchains --detect

    qbs setup-qt %QTDIR%\bin\qmake.exe qt

    qbs config profiles.qt.baseProfile MSVC2015-x86_amd64

    qbs config defaultProfile qt

    qbs --file %APPVEYOR_BUILD_FOLDER% --command-echo-mode command-line --clean-install-root qbs.installRoot:%INSTALL_DIR% %BUILD_VARIANT%

    cd %INSTALL_DIR%\FlightGear_Autopilot

    windeployqt --%BUILD_VARIANT% --no-system-d3d-compiler --no-translations --no-qmltooling --qmldir %APPVEYOR_BUILD_FOLDER%\src\Gui\qml\qml-fgear\modules\FGear %INSTALL_DIR%\FlightGear_Autopilot

    FOR %%G IN ( iconengines imageformats platforms platforminputcontexts scenegraph ) DO ( IF EXIST %%G ( rclone copy %%G data\plugins\%%G\ && rmdir %%G /s /q  && echo "Copied and removed: %%G" ) )

    FOR %%G IN ( Qt QtGraphicalEffects QtQml QtQuick QtQuick.2 Qt3D ) DO ( IF EXIST %%G ( rclone copy %%G data\qml\%%G && rmdir %%G /s /q && echo "Copied and removed: %%G" ) )

    python -u %APPVEYOR_BUILD_FOLDER%/contrib/Qt-Qbs-Application/scripts/take_screenshot.py -f fgautopilot.exe -t 55 -o screenshot.png

    dir

artifacts:
- path: install\FlightGear_Autopilot
  name: Flightgear_Autopilot
- path: install\FlightGear_Autopilot/*.png
  name: screenshot
- path: install\FlightGear_Autopilot/*.log
  name: logs

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
